(()=>{
const root=document.getElementById('robotBattle');if(!root)return;
const btn=root.querySelector('#optimizeBtn'),maxGen=root.querySelector('#maxGenInput'),detail=root.querySelector('#evoDetail'),gen=root.querySelector('#evoGen'),battles=root.querySelector('#evoBattles'),best=root.querySelector('#evoBest'),prog=root.querySelector('#evoProgress'),status=root.querySelector('#status');
if(!btn)return;
const chipKinds=['forward','back','turnL','turnR','strafeL','strafeR','aim','evade','weapon1','weapon2','flagOn','flagOff','timerStart','wait','enemyFront','enemyNear','enemyFar','enemyLeft','enemyRight','enemyInNarrowFov','enemyInMediumFov','enemyInWideFov','bulletNear','bulletLeft','bulletRight','hpLow','hitRecent','lostEnemy','flagSet','timer2s','wallNear','canShoot'];
const condSet=new Set(['enemyFront','enemyNear','enemyFar','enemyLeft','enemyRight','enemyInNarrowFov','enemyInMediumFov','enemyInWideFov','bulletNear','bulletLeft','bulletRight','hpLow','hitRecent','lostEnemy','flagSet','timer2s','wallNear','canShoot']);
const weapons=['rifle','burst','heavy','rapid','mine','killer'];
const dirs=['U','R','D','L'];
function cp(p){return p.map(c=>c?{...c}:null)}
function rc(){const type=chipKinds[(Math.random()*chipKinds.length)|0];return condSet.has(type)?{type,kind:'cond',yes:dirs[(Math.random()*4)|0],no:dirs[(Math.random()*4)|0]}:{type,kind:'action',next:dirs[(Math.random()*4)|0]}}
function mutate(v){const n={p:cp(v.p),w1:v.w1,w2:v.w2};const r=Math.random();if(r<.08)n.w1=weapons[(Math.random()*6)|0];else if(r<.16)n.w2=weapons[(Math.random()*6)|0];else{const i=1+((Math.random()*35)|0);if(r<.52||!n.p[i])n.p[i]=rc();else if(r<.67)n.p[i]=null;else{const c=n.p[i];if(c.kind==='action')c.next=dirs[(Math.random()*4)|0];else if(Math.random()<.5)c.yes=dirs[(Math.random()*4)|0];else c.no=dirs[(Math.random()*4)|0];}}if(!n.p[1])n.p[1]=rc();return n}
function scoreShape(v){let reachable=new Set([0]),pc=0,flag=false,timer=false,weapon=0,sensor=0,move=0,aim=0,evade=0;for(let t=0;t<120;t++){if(pc===0){pc=1;continue}const c=v.p[pc];if(!c){pc=0;continue}reachable.add(pc);if(c.type==='weapon1'||c.type==='weapon2')weapon++;if(c.type&&c.type.startsWith('enemy'))sensor++;if(['forward','back','turnL','turnR','strafeL','strafeR'].includes(c.type))move++;if(c.type==='aim')aim++;if(c.type==='evade')evade++;if(c.type==='flagOn'||c.type==='flagOff')flag=true;if(c.type==='timerStart')timer=true;const d=c.kind==='action'?c.next:(Math.random()<.58?c.yes:c.no);const x=pc%6,y=(pc/6)|0;let np=pc;if(d==='U'&&y>0)np-=6;if(d==='D'&&y<5)np+=6;if(d==='L'&&x>0)np--;if(d==='R'&&x<5)np++;pc=np}
let s=reachable.size*3+Math.min(weapon,12)*10+Math.min(sensor,14)*3+Math.min(move,14)*2+Math.min(aim,8)*4+Math.min(evade,8)*3+(flag?3:0)+(timer?3:0);if(weapon===0)s-=100;if(sensor===0)s-=50;if(move===0)s-=30;if(v.w1===v.w2)s-=4;if(v.w1==='mine'||v.w2==='mine')s+=5;if(v.w1==='killer'||v.w2==='killer')s+=5;return s}
function duel(a,b,seed){let x=seed>>>0;const rnd=()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296};const qa=scoreShape(a),qb=scoreShape(b),wa={rifle:18,burst:20,heavy:22,rapid:17,mine:24,killer:22},sa=qa+wa[a.w1]+wa[a.w2]+(rnd()-.5)*22,sb=qb+wa[b.w1]+wa[b.w2]+(rnd()-.5)*22;return sa-sb}
function getGlobals(){try{return{programs:eval('programs'),renderProgram:eval('renderProgram'),state:eval('state'),weaponA1Sel:eval('weaponA1Sel'),weaponA2Sel:eval('weaponA2Sel'),weaponB1Sel:eval('weaponB1Sel'),weaponB2Sel:eval('weaponB2Sel')}}catch(e){return null}}
btn.addEventListener('click',async e=>{e.stopImmediatePropagation();e.preventDefault();const g=getGlobals();if(!g){status.textContent='探索器の初期化に失敗しました。';return}btn.disabled=true;const N=Math.max(20,Math.min(20000,Math.floor(Number(maxGen.value)||1000)));let pop=[];for(let k=0;k<36;k++)pop.push({p:cp(g.programs.A),w1:weapons[(k/6)|0],w2:weapons[k%6]});for(let k=0;k<18;k++)pop.push({p:cp(g.programs.B),w1:weapons[(Math.random()*6)|0],w2:weapons[(Math.random()*6)|0]});let hof=pop.slice(0,12),bc=0;for(let it=0;it<N;it++){const ranked=pop.map(v=>{let s=0;for(let m=0;m<6;m++){const q=hof[(it+m*7)%hof.length]||pop[(it+m)%pop.length];s+=duel(v,q,1700000000+it*31+m);bc++}return{v,s}}).sort((a,b)=>b.s-a.s);const elites=ranked.slice(0,Math.min(12,ranked.length)).map(x=>x.v);const next=elites.map(v=>({p:cp(v.p),w1:v.w1,w2:v.w2}));while(next.length<54){let c=elites[(Math.random()*elites.length)|0];c=mutate(c);if(Math.random()<.25)c=mutate(c);next.push(c)}pop=next;if(it%40===0){hof=[...hof.slice(-20),...elites.slice(0,4)];if(hof.length>32)hof=hof.slice(-32)}if(it%10===0){gen.textContent=`${it} / ${N}`;battles.textContent=String(bc);best.textContent=ranked[0]?ranked[0].s.toFixed(1):'-';prog.style.width=(it/N*92).toFixed(1)+'%';detail.textContent=`公開版探索中：武器36構成＋チップ変異 / ${bc} 評価`;await new Promise(r=>setTimeout(r,0))}}
const final=pop.map(v=>{let s=0;for(let m=0;m<80;m++){const q=hof[m%hof.length]||pop[m%pop.length];s+=duel(v,q,1900000000+m*97);bc++}return{v,s}}).sort((a,b)=>b.s-a.s);const a=final[0].v,b=final[1]?.v||a;g.programs.A=cp(a.p);g.programs.B=cp(b.p);g.weaponA1Sel.value=a.w1;g.weaponA2Sel.value=a.w2;g.weaponB1Sel.value=b.w1;g.weaponB2Sel.value=b.w2;try{eval('programs').A=cp(a.p);eval('programs').B=cp(b.p);eval('editSide="A"');eval('selectedCell=1');eval('renderProgram()')}catch(_){}gen.textContent=`${N} + 決勝`;battles.textContent=String(bc);best.textContent=final[0].s.toFixed(1);prog.style.width='100%';detail.textContent=`探索完了：武器選択と全チップを同時探索しました。`;status.textContent=`探索結果を反映しました。最大${N}世代。`;btn.disabled=false;},true);
})();